use_frameworks!

target 'KACyclePageView_Example' do
  pod 'KACyclePageView', :path => '../'

  target 'KACyclePageView_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'XCGLogger'
end
